import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const tauriConfig = JSON.parse(
  readFileSync('src-tauri/tauri.conf.json', 'utf8'),
)
const capability = JSON.parse(
  readFileSync('src-tauri/capabilities/default.json', 'utf8'),
)
const buildScript = readFileSync('src-tauri/build.rs', 'utf8')
const rustCommands = readFileSync('src-tauri/src/commands.rs', 'utf8')
const rustLan = readFileSync('src-tauri/src/lan.rs', 'utf8')
const tauriBridge = readFileSync('src/lib/desktop/tauriBridge.ts', 'utf8')
const css = readFileSync('src/index.css', 'utf8')
const packageJson = JSON.parse(readFileSync('package.json', 'utf8'))
const indexHtml = readFileSync('index.html', 'utf8')
const viteConfig = readFileSync('vite.config.ts', 'utf8')
const vercelConfig = JSON.parse(readFileSync('vercel.json', 'utf8'))

const desktopCommands = [
  'project_autosave',
  'project_read_autosave',
  'project_read_recent_snapshots',
  'project_write_recent_snapshot',
  'project_save_file',
  'project_save_ref',
  'project_open_file',
  'project_open_ref',
  'project_export_fountain',
  'project_import_fountain',
  'project_import_fdx',
  'project_export_fdx',
  'project_import_docx',
  'project_export_docx',
  'project_export_pdf',
  'collaboration_lan_host',
  'collaboration_lan_join',
  'collaboration_lan_transport_open',
  'collaboration_lan_transport_send',
  'collaboration_lan_transport_close',
  'collaboration_lan_stop',
  'collaboration_lan_status',
  'bootstrap_installation',
  'installation_get_state',
  'installation_set_tutorial_completed',
]

describe('Pass 2 webview and IPC security boundary', () => {
  it('enforces the restrictive production CSP', () => {
    const csp = tauriConfig.app.security.csp as string

    expect(csp).toContain("default-src 'self'")
    expect(csp).toContain("script-src 'self'")
    expect(csp).toContain("style-src 'self' 'unsafe-inline'")
    expect(csp).toContain("font-src 'self'")
    expect(csp).toContain("img-src 'self' data: blob:")
    expect(csp).toContain(
      "connect-src 'self' ipc: http://ipc.localhost wss://signaling.yjs.dev",
    )
    expect(csp).toContain("object-src 'none'")
    expect(csp).toContain("frame-src 'none'")
    expect(csp).toContain("base-uri 'none'")
    expect(csp).not.toContain('https://fonts.googleapis.com')
    expect(csp).not.toContain('https://fonts.gstatic.com')
  })

  it('bundles the existing fonts without remote stylesheet loading', () => {
    expect(css).not.toContain('fonts.googleapis.com')
    expect(css).not.toContain('fonts.gstatic.com')
    expect(css).toContain('@font-face')
    expect(css).toContain('@fontsource-variable/inter/files/')
    expect(css).toContain('@fontsource/courier-prime/files/')
    expect(packageJson.dependencies['@fontsource-variable/inter']).toBeTruthy()
    expect(packageJson.dependencies['@fontsource/courier-prime']).toBeTruthy()
    expect(
      existsSync(
        'node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2',
      ),
    ).toBe(true)
    expect(
      existsSync(
        'node_modules/@fontsource/courier-prime/files/courier-prime-latin-400-normal.woff2',
      ),
    ).toBe(true)
  })

  it('grants only the core and updater operations used by the UI', () => {
    expect(capability.permissions).not.toContain('core:default')
    expect(capability.permissions).toEqual(
      expect.arrayContaining([
        'core:event:allow-listen',
        'core:event:allow-unlisten',
        'core:window:allow-destroy',
        'process:allow-restart',
        'updater:allow-check',
        'updater:allow-download-and-install',
      ]),
    )
    expect(capability.permissions).not.toContain('updater:default')
  })

  it('registers and explicitly permits every custom Rust command', () => {
    for (const command of desktopCommands) {
      expect(buildScript).toContain(`"${command}"`)
      expect(capability.permissions).toContain(
        `allow-${command.replaceAll('_', '-')}`,
      )
      expect(
        existsSync(`src-tauri/permissions/autogenerated/${command}.toml`),
      ).toBe(true)
    }
  })

  it('removes raw-path project commands from the IPC surface', () => {
    expect(buildScript).not.toContain('"project_save_path"')
    expect(buildScript).not.toContain('"project_open_path"')
    expect(rustCommands).not.toContain('pub fn project_save_path')
    expect(rustCommands).not.toContain('pub fn project_open_path')
    expect(rustCommands).not.toContain('file_path: String')
    expect(tauriBridge).not.toContain('project_save_path')
    expect(tauriBridge).not.toContain('project_open_path')
    expect(tauriBridge).not.toContain('filePath')
  })

  it('applies a restrictive CSP and security headers to the production website', () => {
    expect(indexHtml).not.toContain('http-equiv="Content-Security-Policy"')
    expect(viteConfig).toContain('productionSecurityPolicy')
    const headers = vercelConfig.headers[0].headers as Array<{
      key: string
      value: string
    }>
    const headerMap = Object.fromEntries(
      headers.map(({ key, value }) => [key, value]),
    )
    expect(headerMap['Content-Security-Policy']).toContain(
      "script-src 'self'",
    )
    expect(headerMap['Content-Security-Policy']).toContain(
      "frame-ancestors 'none'",
    )
    expect(headerMap['X-Content-Type-Options']).toBe('nosniff')
    expect(headerMap['X-Frame-Options']).toBe('DENY')
  })

  it('bounds text and binary export payloads before allocation and file writes', () => {
    expect(rustCommands).toContain('EXPORT_TEXT_LIMIT')
    expect(rustCommands).toContain('EXPORT_BINARY_LIMIT')
    expect(rustCommands).toContain('MAX_BASE64_EXPORT_BYTES')
    expect(rustCommands).toContain('base64.len() > encoded_limit')
    expect(rustCommands).toContain('bytes.len() > limit')
    expect(rustCommands).toContain(
      'decode_export_payload_with_limit(base64, EXPORT_BINARY_LIMIT)',
    )
  })

  it('bounds LAN room identifiers and concurrent client transports', () => {
    expect(rustLan).toContain('MAX_TRANSPORT_SESSIONS')
    expect(rustLan).toContain('validate_room_id')
    expect(rustLan).toContain('try_acquire_owned')
  })
})
