import { existsSync, readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

const tauriConfig = JSON.parse(
  readFileSync('src-tauri/tauri.conf.json', 'utf8'),
)
const capability = JSON.parse(
  readFileSync('src-tauri/capabilities/default.json', 'utf8'),
)
const buildScript = readFileSync('src-tauri/build.rs', 'utf8')
const rustCommands = readFileSync('src-tauri/src/commands.rs', 'utf8')
const tauriBridge = readFileSync('src/lib/desktop/tauriBridge.ts', 'utf8')
const css = readFileSync('src/index.css', 'utf8')
const packageJson = JSON.parse(readFileSync('package.json', 'utf8'))

const desktopCommands = [
  'project_autosave',
  'project_read_autosave',
  'project_read_recent_snapshots',
  'project_write_recent_snapshot',
  'project_save_file',
  'project_save_ref',
  'project_open_file',
  'project_open_ref',
  'project_export_fountain',
  'project_import_fountain',
  'project_import_fdx',
  'project_export_fdx',
  'project_import_docx',
  'project_export_docx',
  'project_export_pdf',
  'collaboration_lan_host',
  'collaboration_lan_join',
  'collaboration_lan_transport_open',
  'collaboration_lan_transport_send',
  'collaboration_lan_transport_close',
  'collaboration_lan_stop',
  'collaboration_lan_status',
  'bootstrap_installation',
  'installation_get_state',
  'installation_set_tutorial_completed',
]

describe('Pass 2 webview and IPC security boundary', () => {
  it('enforces the restrictive production CSP', () => {
    const csp = tauriConfig.app.security.csp as string

    expect(csp).toContain("default-src 'self'")
    expect(csp).toContain("script-src 'self'")
    expect(csp).toContain("style-src 'self' 'unsafe-inline'")
    expect(csp).toContain("font-src 'self'")
    expect(csp).toContain("img-src 'self' data: blob:")
    expect(csp).toContain(
      "connect-src 'self' ipc: http://ipc.localhost wss://signaling.yjs.dev",
    )
    expect(csp).toContain("object-src 'none'")
    expect(csp).toContain("frame-src 'none'")
    expect(csp).toContain("base-uri 'none'")
    expect(csp).not.toContain('https://fonts.googleapis.com')
    expect(csp).not.toContain('https://fonts.gstatic.com')
  })

  it('bundles the existing fonts without remote stylesheet loading', () => {
    expect(css).not.toContain('fonts.googleapis.com')
    expect(css).not.toContain('fonts.gstatic.com')
    expect(css).toContain('@font-face')
    expect(css).toContain('@fontsource-variable/inter/files/')
    expect(css).toContain('@fontsource/courier-prime/files/')
    expect(packageJson.dependencies['@fontsource-variable/inter']).toBeTruthy()
    expect(packageJson.dependencies['@fontsource/courier-prime']).toBeTruthy()
    expect(
      existsSync(
        'node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2',
      ),
    ).toBe(true)
    expect(
      existsSync(
        'node_modules/@fontsource/courier-prime/files/courier-prime-latin-400-normal.woff2',
      ),
    ).toBe(true)
  })

  it('grants only the core and updater operations used by the UI', () => {
    expect(capability.permissions).not.toContain('core:default')
    expect(capability.permissions).toEqual(
      expect.arrayContaining([
        'core:event:allow-listen',
        'core:event:allow-unlisten',
        'core:window:allow-destroy',
        'process:allow-restart',
        'updater:allow-check',
        'updater:allow-download-and-install',
      ]),
    )
    expect(capability.permissions).not.toContain('updater:default')
  })

  it('registers and explicitly permits every custom Rust command', () => {
    for (const command of desktopCommands) {
      expect(buildScript).toContain(`"${command}"`)
      expect(capability.permissions).toContain(
        `allow-${command.replaceAll('_', '-')}`,
      )
      expect(
        existsSync(`src-tauri/permissions/autogenerated/${command}.toml`),
      ).toBe(true)
    }
  })

  it('removes raw-path project commands from the IPC surface', () => {
    expect(buildScript).not.toContain('"project_save_path"')
    expect(buildScript).not.toContain('"project_open_path"')
    expect(rustCommands).not.toContain('pub fn project_save_path')
    expect(rustCommands).not.toContain('pub fn project_open_path')
    expect(rustCommands).not.toContain('file_path: String')
    expect(tauriBridge).not.toContain('project_save_path')
    expect(tauriBridge).not.toContain('project_open_path')
    expect(tauriBridge).not.toContain('filePath')
  })
})
