import { expect, test } from '@playwright/test'

test('hosted landing, Use Web and every download format', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('img', { name: 'MasterScript logo' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Use Web' })).toBeVisible()
  await expect(page.getByRole('link', { name: 'Download' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'New Project' })).toHaveCount(0)
  await page.screenshot({ path: 'test-results/landing.png' })
  await page.getByRole('link', { name: 'Download', exact: false }).click()
  for (const extension of ['.exe installer', '.dmg', '.AppImage', '.deb', '.rpm', '.pkg.tar.zst']) await expect(page.locator('.download-format').filter({ hasText: extension })).toBeVisible()
  await expect(page.getByText('yay -S masterscript-bin')).toHaveCount(0)
  const downloads = page.locator('a.download-option')
  await expect(downloads).toHaveCount(9)
  for (const link of await downloads.all()) expect(await link.getAttribute('href')).toContain('/releases/latest/download/')
  await page.screenshot({ path: 'test-results/downloads.png', fullPage: true })
  await page.getByRole('link', { name: 'Use Web' }).click()
  await expect(page.getByRole('heading', { name: 'Welcome to your writing workspace' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'New Project', exact: true })).toBeVisible()
  await expect(page.locator('a[href*="releases/latest/download"]')).toHaveCount(0)
})

test('Enter splits real editor data, restores caret, and supports undo/redo and reload', async ({ page }) => {
  await page.goto('/#/app')
  await page.getByRole('button', { name: 'New Project', exact: true }).click()
  const skip = page.getByRole('button', { name: /skip|close tutorial/i })
  if (await skip.count()) await skip.first().click()
  const heading = page.getByRole('textbox', { name: 'scene-heading screenplay block' }).first()
  await heading.fill('INT. HOSPITAL - NIGHT')
  await heading.press('End')
  await heading.press('Enter')
  const action = page.getByRole('textbox', { name: 'action screenplay block' }).first()
  await expect(action).toBeFocused()
  await action.fill('RAVI lies on the bed and sees Maya.')
  await action.press('Home')
  for (let i = 0; i < 20; i++) await action.press('ArrowRight')
  await action.press('Enter')
  await expect(action).toHaveText('RAVI lies on the bed ')
  const right = page.getByRole('textbox', { name: 'character screenplay block' }).first()
  await expect(right).toHaveText('and sees Maya.')
  await expect(right).toBeFocused()
  await right.press('Control+z')
  await expect(action).toHaveText('RAVI lies on the bed and sees Maya.')
  await action.press('Control+y')
  await expect(right).toHaveText('and sees Maya.')
  await page.waitForTimeout(1800)
  await page.reload()
  // Recovery returns to the application home. The serialized autosave is the authority.
  const saved = await page.evaluate(() => Object.entries(localStorage).map(([,value]) => { try { return JSON.parse(value) } catch { return null } }).find(value => value?.blocks?.some((block: { text: string }) => block.text === 'and sees Maya.')))
  expect(saved.blocks.some((block: { text: string }) => block.text.trim() === 'RAVI lies on the bed')).toBe(true)
})

test('landing remains usable on a narrow screen', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('link', { name: 'Use Web' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390)
})

test('automatic breakdown edits, rejections and report exports share the saved project', async ({ page }) => {
  await page.goto('/#/app')
  await page.getByRole('button', { name: 'New Project', exact: true }).click()
  const heading = page.getByRole('textbox', { name: 'scene-heading screenplay block' }).first()
  await heading.fill('INT. HOSPITAL - NIGHT')
  await heading.press('End')
  await heading.press('Enter')
  await page.getByRole('textbox', { name: 'action screenplay block' }).first().fill("RAVI lies unconscious on the bed. Maya enters carrying Ravi's backpack. A NURSE follows her. She checks the heart monitor.")
  await page.getByRole('button', { name: 'Breakdown', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Scene Breakdown' })).toBeVisible()
  const bag = page.locator('.tag-catalog-item').filter({ has: page.locator('input[value="backpack"]') })
  await expect(bag).toBeVisible()
  await bag.getByLabel('Notes').fill('Hero prop')
  await bag.getByLabel('Cost').fill('25')
  await bag.getByLabel('Item', { exact: true }).fill('Ravi bag')
  const edited = page.locator('.tag-catalog-item').filter({ has: page.locator('input[value="Ravi bag"]') })
  await page.getByRole('button', { name: 'Reanalyse', exact: true }).click()
  await expect(edited.getByLabel('Notes')).toHaveValue('Hero prop')
  await expect(edited.getByLabel('Cost')).toHaveValue('25')
  const monitor = page.locator('.tag-catalog-item').filter({ has: page.locator('input[value="heart monitor"]') })
  await monitor.getByRole('button', { name: 'Reject', exact: true }).click()
  await page.getByRole('button', { name: 'Reanalyse', exact: true }).click()
  await expect(monitor).toHaveCount(0)
  const overflowingFields = await page.locator('.tag-catalog-item').evaluateAll(items => items.flatMap(item => {
    const card = item.getBoundingClientRect()
    return [...item.querySelectorAll('input, select')].filter(field => field.getBoundingClientRect().right > card.right + 1)
  }).length)
  expect(overflowingFields).toBe(0)
  await page.screenshot({ path: 'test-results/breakdown.png', fullPage: true })
  await page.getByRole('button', { name: 'Reports', exact: true }).click()
  await expect(page.getByText('Ravi bag', { exact: false }).first()).toBeVisible()
  await page.getByLabel('Report type').selectOption('department')
  await page.getByLabel('Report department').selectOption('Props')
  await expect(page.locator('.report-table').getByText('Hero prop', { exact: true })).toBeVisible()
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export CSV', exact: true }).click()
  expect((await download).suggestedFilename()).toMatch(/\.csv$/)
  await page.waitForTimeout(1600)
  const saved = await page.evaluate(() => Object.values(localStorage).map(value => { try { return JSON.parse(value) } catch { return null } }).find(value => value?.tagging?.catalog?.some((item: { name: string }) => item.name === 'Ravi bag')))
  expect(saved.tagging.rejectedItems).toContain('Set Dressing:heart monitor')
})
